# Deep Learning - Project 2

In [24]:
import torch
import math

In [ ]:
torch.set_grad_enabled(False)

#### Class

There are 2 ways to generate the forward pass:
- either give a single sample as input (vector implies the use of mv), and apply the formula: 
$$
\begin{aligned}
a^{(1)} = \sigma(Wa^{(0)} + b)
\end{aligned}
$$

- or give all the training as input, i.e. a vector of (nb_samples, nb_features) using the formula 
$$
\begin{aligned}
a^{(1)} = \sigma(a^{(0)} * W + b)
\end{aligned}
$$

where $a = [nb samples, nb features]$, $W = [nb features, nb hidden]$, $aW = [nb samples, nb hidden]$ and $b = [nb hidden]$

In [ ]:
class Module(object):
    def __init__(self, weights, bias, act_fct, d_act_fct):
        self.W = weights
        self.b = bias
        self.act = act_fct
        self.dact = d_act_fct
    
    def forward(self, input_data):
        '''
        Compute the output tensor  
        '''
        return # a * W

    
    def backward(self, *gradwrtoutput):
        raise tobecontinued
    
    def param(self):
        return []

#### Activation functions

$tanh(x) = \frac{e^x - e^{-x}}{e^x + e^{-x}}$

$\frac{d}{dx}tanh(x) = \frac{4}{(e^x + e^{-x})^2}$

In [50]:
def ReLU(x):
    output = torch.clone(x)
    output[x <= 0] = 0
    
    return output
    
def dReLU(x):
    output = torch.clone(x)
    
    output[x > 0] = 1
    output[x <= 0] = 0
    
    return output

def Tanh(x):
    return (x.exp() - x.mul(-1).exp()) * ((x.exp() + x.mul(-1).exp()).pow(-1))

def dTanh(x):
    return 4 * (x.exp() + x.mul(-1).exp()).pow(-2)

#### Other required functions

In [ ]:
def l2_norm(x, y):
    y_hat = Module.forward(x)
    return ((y_hat - y).pow(2)).sum().item()

def lossMSE(x, y):
    '''
    Compute the mean squared error (MSE) between the x and y input tensors
    '''
    return ((x - y).pow(2)).mean().item()

def dlossMSE(x, y):
    return (2 * (x - y)).mean().item()

#def Linear()

#def Sequential()

In [ ]:
def testing_error(test_set):
    nb_errors = 0
    # ...
    

In [51]:
# Check
test_tensor = torch.Tensor([[1,-4,2], [0,6,-5]])
print(test_tensor)
print(ReLU(test_tensor))

print(test_tensor.tanh()) #PyTorch function
print(Tanh(test_tensor))

tensor([[ 1., -4.,  2.],
        [ 0.,  6., -5.]])
tensor([[1., 0., 2.],
        [0., 6., 0.]])
tensor([[ 0.7616, -0.9993,  0.9640],
        [ 0.0000,  1.0000, -0.9999]])
tensor([[ 0.7616, -0.9993,  0.9640],
        [ 0.0000,  1.0000, -0.9999]])


#### Generate train + test sets

In [43]:
# Training set
def generate_sets(nb_train = 1000, nb_test = 1000):
    # data
    train_set = torch.Tensor(nb_train, 2).uniform_(0, 1)
    test_set = torch.Tensor(nb_test, 2).uniform_(0, 1)
    # labels
    train_target = train_set.pow(2).sum(1).sub(1 / math.sqrt(2 * math.pi)).sign().long()
    test_target = test_set.pow(2).sum(1).sub(1 / math.sqrt(2 * math.pi)).sign().long()
    
    return train_set, test_set, train_target, test_target
    

In [47]:
train_, test_, train_labels, test_labels = generate_sets()
print(train_.shape)
print(test_.shape)
print(train_labels.shape)
print(test_labels.shape)

torch.Size([1000, 2])
torch.Size([1000, 2])
torch.Size([1000])
torch.Size([1000])
